/* ═══════════════════════════════════════════════════════════════
   OMNIS — Solar System Real Astronomical Data
   ═══════════════════════════════════════════════════════════════ */

// All distances in AU, masses relative to Earth, radii relative to Earth
export const SOLAR_SYSTEM = {
    star: {
        name: 'The Sun',
        type: 'STAR',
        spectralClass: 'G2V',
        massKg: '1.989 × 10³⁰ kg',
        radiusKm: '696,340 km',
        tempK: 5778,
        tempDisplay: '5,778 K',
        age: '4.6 Gyr',
        luminosity: 1.0,
        color: 0xffcc44,
        renderRadius: 4.0,
    },
    planets: [
        {
            name: 'Mercury',
            type: 'PLANET',
            classification: 'Terrestrial',
            massKg: '3.301 × 10²³ kg',
            massEarth: 0.055,
            radiusKm: '2,439.7 km',
            radiusEarth: 0.383,
            tempK: 440,
            tempDisplay: '167 °C (mean)',
            distAU: 0.387,
            orbitalPeriod: '87.97 days',
            rotationPeriod: '58.65 days',
            axialTilt: 0.034,
            moons: 0,
            atmosphere: 'None (exosphere)',
            renderDist: 8,
            renderRadius: 0.35,
            shaderType: 'rocky',
            shaderParams: { baseColor: [0.45, 0.42, 0.38], craterDensity: 0.7, hasAtmosphere: false },
        },
        {
            name: 'Venus',
            type: 'PLANET',
            classification: 'Terrestrial',
            massKg: '4.867 × 10²⁴ kg',
            massEarth: 0.815,
            radiusKm: '6,051.8 km',
            radiusEarth: 0.950,
            tempK: 737,
            tempDisplay: '464 °C',
            distAU: 0.723,
            orbitalPeriod: '224.7 days',
            rotationPeriod: '243 days (retro)',
            axialTilt: 177.4,
            moons: 0,
            atmosphere: '96.5% CO₂, 3.5% N₂',
            renderDist: 12,
            renderRadius: 0.55,
            shaderType: 'venus',
            shaderParams: { baseColor: [0.85, 0.65, 0.30], cloudDensity: 1.0 },
        },
        {
            name: 'Earth',
            type: 'PLANET',
            classification: 'Terrestrial',
            massKg: '5.972 × 10²⁴ kg',
            massEarth: 1.0,
            radiusKm: '6,371 km',
            radiusEarth: 1.0,
            tempK: 288,
            tempDisplay: '15 °C',
            distAU: 1.0,
            orbitalPeriod: '365.25 days',
            rotationPeriod: '23.93 hours',
            axialTilt: 23.44,
            moons: 1,
            atmosphere: '78% N₂, 21% O₂, 1% Ar',
            waterCoverage: 71,
            habitability: 98,
            biosphere: 'Complex Multicellular',
            population: '8.1 billion',
            techLevel: 'Type 0.73',
            renderDist: 16,
            renderRadius: 0.60,
            shaderType: 'earth',
            shaderParams: {},
            moonData: [
                { name: 'Luna', radiusKm: '1,737.4 km', distKm: '384,400 km', renderDist: 1.8, renderRadius: 0.16 }
            ]
        },
        {
            name: 'Mars',
            type: 'PLANET',
            classification: 'Terrestrial',
            massKg: '6.417 × 10²³ kg',
            massEarth: 0.107,
            radiusKm: '3,389.5 km',
            radiusEarth: 0.532,
            tempK: 210,
            tempDisplay: '-63 °C',
            distAU: 1.524,
            orbitalPeriod: '687 days',
            rotationPeriod: '24.62 hours',
            axialTilt: 25.19,
            moons: 2,
            atmosphere: '95.3% CO₂, 2.7% N₂',
            renderDist: 21,
            renderRadius: 0.45,
            shaderType: 'mars',
            shaderParams: {},
            moonData: [
                { name: 'Phobos', radiusKm: '11.3 km', distKm: '9,376 km', renderDist: 1.0, renderRadius: 0.04 },
                { name: 'Deimos', radiusKm: '6.2 km', distKm: '23,460 km', renderDist: 1.4, renderRadius: 0.03 }
            ]
        },
        {
            name: 'Jupiter',
            type: 'PLANET',
            classification: 'Gas Giant',
            massKg: '1.898 × 10²⁷ kg',
            massEarth: 317.8,
            radiusKm: '69,911 km',
            radiusEarth: 10.97,
            tempK: 165,
            tempDisplay: '-108 °C',
            distAU: 5.203,
            orbitalPeriod: '11.86 years',
            rotationPeriod: '9.93 hours',
            axialTilt: 3.13,
            moons: 95,
            atmosphere: '89.8% H₂, 10.2% He',
            renderDist: 34,
            renderRadius: 1.6,
            shaderType: 'jupiter',
            shaderParams: {},
            moonData: [
                { name: 'Io', radiusKm: '1,821 km', distKm: '421,700 km', renderDist: 3.0, renderRadius: 0.12 },
                { name: 'Europa', radiusKm: '1,560 km', distKm: '671,100 km', renderDist: 3.8, renderRadius: 0.10 },
                { name: 'Ganymede', radiusKm: '2,634 km', distKm: '1.07M km', renderDist: 4.5, renderRadius: 0.14 },
                { name: 'Callisto', radiusKm: '2,410 km', distKm: '1.88M km', renderDist: 5.5, renderRadius: 0.13 },
            ]
        },
        {
            name: 'Saturn',
            type: 'PLANET',
            classification: 'Gas Giant',
            massKg: '5.683 × 10²⁶ kg',
            massEarth: 95.16,
            radiusKm: '58,232 km',
            radiusEarth: 9.14,
            tempK: 134,
            tempDisplay: '-139 °C',
            distAU: 9.537,
            orbitalPeriod: '29.46 years',
            rotationPeriod: '10.66 hours',
            axialTilt: 26.73,
            moons: 146,
            atmosphere: '96.3% H₂, 3.25% He',
            hasRings: true,
            renderDist: 50,
            renderRadius: 1.35,
            shaderType: 'saturn',
            shaderParams: {},
            moonData: [
                { name: 'Titan', radiusKm: '2,575 km', distKm: '1.22M km', renderDist: 4.0, renderRadius: 0.14 },
                { name: 'Enceladus', radiusKm: '252 km', distKm: '238,000 km', renderDist: 2.8, renderRadius: 0.05 },
            ]
        },
        {
            name: 'Uranus',
            type: 'PLANET',
            classification: 'Ice Giant',
            massKg: '8.681 × 10²⁵ kg',
            massEarth: 14.54,
            radiusKm: '25,362 km',
            radiusEarth: 3.98,
            tempK: 76,
            tempDisplay: '-197 °C',
            distAU: 19.19,
            orbitalPeriod: '84.01 years',
            rotationPeriod: '17.24 hours',
            axialTilt: 97.77,
            moons: 27,
            atmosphere: '82.5% H₂, 15.2% He, 2.3% CH₄',
            hasRings: true,
            renderDist: 68,
            renderRadius: 0.85,
            shaderType: 'iceGiant',
            shaderParams: { baseColor: [0.55, 0.82, 0.87], bandIntensity: 0.15 },
        },
        {
            name: 'Neptune',
            type: 'PLANET',
            classification: 'Ice Giant',
            massKg: '1.024 × 10²⁶ kg',
            massEarth: 17.15,
            radiusKm: '24,622 km',
            radiusEarth: 3.87,
            tempK: 72,
            tempDisplay: '-201 °C',
            distAU: 30.07,
            orbitalPeriod: '164.8 years',
            rotationPeriod: '16.11 hours',
            axialTilt: 28.32,
            moons: 16,
            atmosphere: '80% H₂, 19% He, 1.5% CH₄',
            renderDist: 82,
            renderRadius: 0.80,
            shaderType: 'iceGiant',
            shaderParams: { baseColor: [0.15, 0.20, 0.65], bandIntensity: 0.25 },
            moonData: [
                { name: 'Triton', radiusKm: '1,353 km', distKm: '354,800 km', renderDist: 2.5, renderRadius: 0.09 },
            ]
        }
    ]
};

// Star spectral types for procedural star generation
export const SPECTRAL_TYPES = [
    { type: 'O', temp: 33000, color: 0x9bb0ff, luminosity: 30000, radius: 6.6, rarity: 0.003 },
    { type: 'B', temp: 20000, color: 0xaabfff, luminosity: 2000, radius: 3.5, rarity: 0.01 },
    { type: 'A', temp: 8500, color: 0xcad7ff, luminosity: 25, radius: 1.7, rarity: 0.05 },
    { type: 'F', temp: 6700, color: 0xf8f7ff, luminosity: 2.5, radius: 1.3, rarity: 0.10 },
    { type: 'G', temp: 5800, color: 0xfff4ea, luminosity: 1.0, radius: 1.0, rarity: 0.15 },
    { type: 'K', temp: 4400, color: 0xffd2a1, luminosity: 0.3, radius: 0.7, rarity: 0.25 },
    { type: 'M', temp: 3200, color: 0xffb56c, luminosity: 0.04, radius: 0.3, rarity: 0.42 },
];

// Exotic object types
export const EXOTIC_TYPES = [
    { type: 'Black Hole', rarity: 0.005, renderRadius: 2.0 },
    { type: 'Neutron Star', rarity: 0.01, renderRadius: 0.3 },
    { type: 'White Dwarf', rarity: 0.08, renderRadius: 0.15 },
    { type: 'Red Giant', rarity: 0.05, renderRadius: 8.0 },
    { type: 'Brown Dwarf', rarity: 0.15, renderRadius: 0.2 },
];

// Galaxy morphology types
export const GALAXY_TYPES = [
    { type: 'Spiral', code: 'Sa-Sc', rarity: 0.60 },
    { type: 'Elliptical', code: 'E0-E7', rarity: 0.25 },
    { type: 'Irregular', code: 'Irr', rarity: 0.10 },
    { type: 'Lenticular', code: 'S0', rarity: 0.05 },
];

/* ═══════════════════════════════════════════════════════════════
   INTERSTELLAR SYSTEM (EASTER EGG)
   ═══════════════════════════════════════════════════════════════ */
export const INTERSTELLAR_SYSTEM = {
    star: {
        name: 'Gargantua',
        type: 'EXOTIC',
        classification: 'Supermassive Black Hole',
        massKg: '100 Million M☉',
        radiusKm: '1.5 × 10⁸ km',
        tempK: 0,
        tempDisplay: 'Unknown',
        age: 'Unknown',
        luminosity: 0,
        color: 0x000000,
        renderRadius: 8.0,
        isBlackHole: true
    },
    planets: [
        {
            name: "Miller's Planet",
            type: 'PLANET',
            classification: 'Ocean World',
            massKg: 'Unknown',
            massEarth: 1.3,
            radiusKm: 'Unknown',
            radiusEarth: 1.2,
            tempK: 280,
            tempDisplay: '7 °C',
            distAU: 0.1,
            orbitalPeriod: '1.7 hours',
            rotationPeriod: 'Tidally locked',
            axialTilt: 0,
            moons: 0,
            atmosphere: 'Breathable, high gravity',
            renderDist: 20,
            renderRadius: 0.6,
            shaderType: 'waterWorld',
            isMiller: true
        },
        {
            name: "Mann's Planet",
            type: 'PLANET',
            classification: 'Ice World',
            massKg: 'Unknown',
            massEarth: 0.9,
            radiusKm: 'Unknown',
            radiusEarth: 0.95,
            tempK: 150,
            tempDisplay: '-123 °C',
            distAU: 2.5,
            orbitalPeriod: 'Unknown',
            rotationPeriod: 'Unknown',
            axialTilt: 0,
            moons: 0,
            atmosphere: 'Ammonia, toxic',
            renderDist: 40,
            renderRadius: 0.5,
            shaderType: 'iceWorld',
            isMann: true
        },
        {
            name: "Edmunds' Planet",
            type: 'PLANET',
            classification: 'Terrestrial Desert',
            massKg: 'Unknown',
            massEarth: 1.0,
            radiusKm: 'Unknown',
            radiusEarth: 1.0,
            tempK: 290,
            tempDisplay: '17 °C',
            distAU: 4.0,
            orbitalPeriod: 'Unknown',
            rotationPeriod: 'Unknown',
            axialTilt: 0,
            moons: 0,
            atmosphere: 'Breathable',
            renderDist: 60,
            renderRadius: 0.55,
            shaderType: 'rocky',
            shaderParams: { baseColor: [0.7, 0.5, 0.4] }
        }
    ]
};
